from abc import ABC, abstractmethod

class IGeoServerService(ABC):
    @abstractmethod
    def create_style_registration(self, name: str, workspace: str, filename: str) -> None: ...
    @abstractmethod
    def upload_style_sld(self, name: str, workspace: str, sld_xml: str) -> None: ...
    @abstractmethod
    def create_featuretype(self, workspace: str, datastore: str, layer: str) -> None: ...
    @abstractmethod
    def set_default_style(self, layer: str, workspace: str, style: str) -> None: ...
    @abstractmethod
    def get_style_sld_length(self, workspace: str, name: str) -> int | None: ...
    @abstractmethod
    def check_layer_status(self, layer: str, workspace: str) -> int: ...
